### ISSUE TITLE
Python examples

### ISSUE THREAD

**Issue by ir4y** [openhealthhub/FhirClients#29]
Hi,
Thank you for using https://github.com/beda-software/fhir-py/

I am checking how my project is used by other software engineers and found your repo in crosslinks.
I checked [CarePlan examples ](https://github.com/openhealthhub/FhirClients/blob/main/python/careplan/careplan.py#L27) and find out that you are using `execute` operation for resource saving, deleting, etc.
However, the library provides [dedicated functions ](https://github.com/beda-software/fhir-py#asyncfhirresource) for saving, deleting, etc.

I am just wondering why you do it this way. Are there any FHIR server limitations that force you with such an approach?
I would like to get more details if it is possible.

Best,
Ilya

**Comment by esbakker** [comment]
Hi Ilya,

Thanks for checking out our code. We're not Python developers, and the purpose of this code is for implementors of our API to have some examples in multiple languages to get started (see [developer.openhealthhub.com](https://developer.openhealthhub.com) for more info). So we might have taken some shortcuts. The issue here is I think that we just read plain JSON from a file and thus don't have a FHIR resource object on which we can call these functions.
For delete we could have used the `delete` function I see.

But you're free to create a PR to improve these examples of course :).

Best,
Eddy

**Comment by dmitryashutov** [comment]
Hello everyone! I'm preparing the [PR](https://github.com/openhealthhub/FhirClients/pull/33), please take a look at it. During the work I was trying to check the examples using your sandbox but faced some problems.

For instance, I created a CarePlan resource via `POST {{baseUrl}}CarePlan` and received a resource with generated ID. Then I tried to update this resource via `PUT {{baseUrl}}CarePlan/<created-careplan-id>`. I added `title` field to resource. But for some reason in the response I received the CarePlan with another ID and no title in it. Is it a specific behaviour of the Sandbox? Is it possible to test my code in more realistic environment? Thanks in advance.

**Comment by esbakker** [comment]
Hi,

Thanks for the PR. Looks good 👍.

That you can't update the title is partly because the sandbox uses fixed resources, so we don't store any data, we'll just return a default response and replace some fields based on the request.

But even if the CarePlan had a title (which it should have, but we still have to add that) you wouldn't be able to update it because of our business logic.
We currently only have the sandbox and the real production environment for customers, so I don't think we have a more realistic environment available for you.

**Comment by dmitryashutov** [comment]
Hi @esbakker! Thank you for your answer. I've made minor improvements in the PR #33. So could you review it and merge if there are no any  suggestions or notes from your side. Thanks in advance!
